# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

{{- if .Values.stunner.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "release.fullname" . }}-stunner-gw
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ include "release.fullname" . }}-stunner
  listeners:
    - name: udp-listener
      port: {{ .Values.stunner.gateway.port }}
      protocol: TURN-UDP
{{- end }}
