# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Service
metadata:
  name: {{ include "fintech.complexName" . }}-ui
spec:
  type: NodePort
  ports:
    - port: {{ .Values.ports.ui }}
      targetPort: {{ .Values.ports.ui }}
  selector:
    app: {{ include "fintech.complexName" . }}-ui
