# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v2
name: aimsb-llm-chat
description: LLM Chat Sandbox
type: application
maintainers:
- name: AMD
  url: https://www.amd.com/
version: 0.6.4
dependencies:
- name: aimchart-llm
  version: 0.2.1
  repository: oci://registry-1.docker.io/amdenterpriseai
  alias: llm
annotations:
  org.opencontainers.image.vendor: AMD
  com.amd.aim.release.notes: "Update AIM version"
  com.amd.aim.description.full: Get a feel for your LLM in a safe sandbox. Explore prompting techniques, validate outputs, and understand model behavior before embedding LLMs into critical enterprise workflows.
  com.amd.aim.hfToken.required: "not-applicable"
  com.amd.aim.title: "LLM Chat Sandbox"
