# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v2
name: aimsb-autogenstudio
description: A no-code GUI for building agentic AI applications
type: application
maintainers:
- name: AMD
  url: https://www.amd.com/
version: 0.4.6
appVersion: "0.4.2.2"
dependencies:
- name: aimchart-llm
  version: 0.2.3
  repository: oci://registry-1.docker.io/amdenterpriseai
  alias: llm
annotations:
  org.opencontainers.image.vendor: AMD
  com.amd.aim.title: "AutoGen Studio Agentic Platform"
  com.amd.aim.description.full: "A no-code visual interface for building agentic AI workflows. Design, test, and deploy AI agents that autonomously perform complex tasks by combining language models with custom tools and multi-step workflows."
  com.amd.aim.hfToken.required: "not-applicable"
