#!/usr/bin/env bash
# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

# install_splunk.sh — user-space Splunk Enterprise install on a single machine,
# with the HTTP Event Collector (HEC) enabled and an `axis` index + token
# provisioned for the governance telemetry sink.
#
# Constraints honored (no root required):
#   * unpacks the tgz under $SPLUNK_HOME in the user's home (no system paths),
#   * all ports are >1024 so no privilege is needed,
#   * never touches /etc; writes only under $SPLUNK_HOME.
#
# Idempotent: re-running reuses an existing install and just re-asserts the
# index + token.
#
# Env:
#   SPLUNK_HOME    install dir         (default: $HOME/splunk)
#   SPLUNK_USER    admin user          (default: admin)
#   SPLUNK_PASS    admin password      (default: <SPLUNK_PASS>)
#   SPLUNK_TGZ     path to a pre-downloaded tgz (default: download)
#   SPLUNK_URL     download url if no tgz present
#   HEC_TOKEN      fixed token to provision (default: auto-generated by Splunk)
#   SPLUNK_INDEX   index name          (default: axis)
#   WEB_PORT/MGMT_PORT/HEC_PORT  (defaults: 8000/8089/8088)
#
set -euo pipefail

SPLUNK_HOME="${SPLUNK_HOME:-$HOME/splunk}"
SPLUNK_USER="${SPLUNK_USER:-admin}"
SPLUNK_PASS="${SPLUNK_PASS:?set SPLUNK_PASS}"
SPLUNK_INDEX="${SPLUNK_INDEX:-axis}"
WEB_PORT="${WEB_PORT:-8000}"
MGMT_PORT="${MGMT_PORT:-8089}"
HEC_PORT="${HEC_PORT:-8088}"
SPLUNK="$SPLUNK_HOME/bin/splunk"

log() { printf '[install-splunk] %s\n' "$*"; }

# --- obtain + unpack -------------------------------------------------------
if [ ! -x "$SPLUNK" ]; then
  TGZ="${SPLUNK_TGZ:-}"
  if [ -z "$TGZ" ]; then
    : "${SPLUNK_URL:?set SPLUNK_TGZ (local file) or SPLUNK_URL (download link)}"
    TGZ="$(mktemp "${TMPDIR:-/tmp}/splunk.XXXXXX.tgz")"
    log "downloading Splunk -> $TGZ"
    curl -fL "$SPLUNK_URL" -o "$TGZ"
  fi
  mkdir -p "$(dirname "$SPLUNK_HOME")"
  log "unpacking $TGZ -> $SPLUNK_HOME"
  tar -xzf "$TGZ" -C "$(dirname "$SPLUNK_HOME")"
  # tarball expands to a top-level `splunk/`; if SPLUNK_HOME differs, move it.
  if [ ! -x "$SPLUNK" ] && [ -x "$(dirname "$SPLUNK_HOME")/splunk/bin/splunk" ]; then
    :  # default layout already correct
  fi
fi
[ -x "$SPLUNK" ] || { log "FATAL: splunk binary missing at $SPLUNK"; exit 1; }

# --- seed admin creds before first boot (avoids interactive prompt) --------
SEED="$SPLUNK_HOME/etc/system/local/user-seed.conf"
if [ ! -f "$SPLUNK_HOME/etc/passwd" ]; then
  mkdir -p "$(dirname "$SEED")"
  cat > "$SEED" <<EOF
[user_info]
USERNAME = $SPLUNK_USER
PASSWORD = $SPLUNK_PASS
EOF
  log "seeded admin user"
fi

# --- bind to non-privileged ports -----------------------------------------
WEBCONF="$SPLUNK_HOME/etc/system/local/web.conf"
mkdir -p "$(dirname "$WEBCONF")"
cat > "$WEBCONF" <<EOF
[settings]
httpport = $WEB_PORT
EOF

# mgmt port via splunk-launch / server.conf
"$SPLUNK" set splunkd-port "$MGMT_PORT" --accept-license --answer-yes --no-prompt >/dev/null 2>&1 || true

# --- first start (accept license non-interactively) ------------------------
log "starting splunkd (web=$WEB_PORT mgmt=$MGMT_PORT)"
"$SPLUNK" start --accept-license --answer-yes --no-prompt >/dev/null

auth() { "$SPLUNK" "$@" -auth "$SPLUNK_USER:$SPLUNK_PASS"; }

# --- index ----------------------------------------------------------------
if auth list index 2>/dev/null | grep -q "^${SPLUNK_INDEX}\b"; then
  log "index '$SPLUNK_INDEX' exists"
else
  log "creating index '$SPLUNK_INDEX'"
  auth add index "$SPLUNK_INDEX" >/dev/null
fi

# --- enable HEC + provision a token ---------------------------------------
log "enabling HEC on :$HEC_PORT"
auth http-event-collector enable -uri "https://127.0.0.1:$MGMT_PORT" >/dev/null 2>&1 || true
# global HEC settings: enable, disable SSL? keep SSL on (sink accepts self-signed).
auth http-event-collector update -uri "https://127.0.0.1:$MGMT_PORT" \
  -enable-ssl 1 -port "$HEC_PORT" >/dev/null 2>&1 || true

TOKEN_NAME="axis-orch"
if auth http-event-collector list -uri "https://127.0.0.1:$MGMT_PORT" 2>/dev/null | grep -q "$TOKEN_NAME"; then
  log "HEC token '$TOKEN_NAME' exists"
else
  log "creating HEC token '$TOKEN_NAME' -> index $SPLUNK_INDEX"
  if [ -n "${HEC_TOKEN:-}" ]; then
    auth http-event-collector create "$TOKEN_NAME" \
      -uri "https://127.0.0.1:$MGMT_PORT" \
      -index "$SPLUNK_INDEX" -token "$HEC_TOKEN" >/dev/null
  else
    auth http-event-collector create "$TOKEN_NAME" \
      -uri "https://127.0.0.1:$MGMT_PORT" \
      -index "$SPLUNK_INDEX" >/dev/null
  fi
fi

TOKEN_VALUE="$(auth http-event-collector list -uri "https://127.0.0.1:$MGMT_PORT" 2>/dev/null \
  | grep -A4 "$TOKEN_NAME" | grep -i 'token=' | head -1 | sed 's/.*token=//; s/[ ,].*//')"

log "restarting to apply HEC config"
"$SPLUNK" restart >/dev/null

cat <<EOF

=== Splunk ready ===
  Web UI : http://127.0.0.1:$WEB_PORT  (login: $SPLUNK_USER / $SPLUNK_PASS)
  HEC    : https://127.0.0.1:$HEC_PORT/services/collector/event
  Mgmt   : https://127.0.0.1:$MGMT_PORT
  Index  : $SPLUNK_INDEX
  Token  : ${TOKEN_VALUE:-<see: $SPLUNK http-event-collector list>}

Run the story against it:
  SPLUNK_HEC_URL=https://127.0.0.1:$HEC_PORT \\
  SPLUNK_HEC_TOKEN=${TOKEN_VALUE:-<token>} \\
  SPLUNK_INDEX=$SPLUNK_INDEX \\
  ORCH_SCHEDULER=spur ORCH_SANDBOX_BACKEND=axis ORCH_SANDBOX_POLICY=<policy.yaml> \\
  ./run_story.sh
EOF
