# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

{{- if .Values.agentApp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-agentic-rag-agentic-app-code
  labels:
    app.kubernetes.io/name: {{ include "release.name" . }}
    app.kubernetes.io/component: agent-app
data:
{{- $files := .Files }}
{{- range $path, $_ := .Files.Glob "src/*" }}
  {{ $key := $path | trimPrefix "src/" }}
  {{- $key }}: |
{{ $files.Get $path | nindent 4 }}
{{- end }}
{{- end }}
