# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Service
metadata:
  name: {{ include "router.complexName" . }}-router-classifier
  namespace: {{ .Release.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.routerClassifier }}
      targetPort: {{ .Values.ports.routerClassifier }}
  selector:
    app: {{ include "router.complexName" . }}-router-classifier
