# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "router.complexName" . }}-router-controller
  namespace: {{ .Release.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "router.complexName" . }}-router-controller
  template:
    metadata:
      labels:
        app: {{ include "router.complexName" . }}-router-controller
    spec:
      initContainers:
        - name: unpack-workload
          image: busybox:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              set -eux
              mkdir -p /workload/mount

              for key in $(ls /workload/configmap); do
                content=$(cat "/workload/configmap/$key")

                if echo "$key" | grep -q "__init__.py$"; then
                  filename="__init__.py"
                  dirpart=$(echo "$key" | sed 's/__init__.py$//')
                  dirpath=$(echo "$dirpart" | tr '_' '/')
                else
                  filename=$(echo "$key" | awk -F'_' '{print $NF}')
                  dirpath=$(echo "$key" | sed 's/_'"$filename"'$//; s/_/\//g')
                fi

                mkdir -p "/workload/mount/$dirpath"
                echo "$content" > "/workload/mount/$dirpath/$filename"
              done
          volumeMounts:
            - name: workload
              mountPath: /workload/configmap
            - name: workload-mount
              mountPath: /workload/mount
      containers:
        - name: router-controller
          image: {{ .Values.images.pythonBase }}
          command: [ "sh", "-c" ]
          env:
            - name: CLASSIFIER_CONTEXT_MODE
              value: {{ .Values.secrets.CLASSIFIER_CONTEXT_MODE | quote }}
            - name: CLASSIFIER_CONTEXT_TURNS
              value: {{ .Values.secrets.CLASSIFIER_CONTEXT_TURNS | quote }}
          args:
            - |
              set -e
              pip install -v --no-cache-dir -r /workload/mount/controller/requirements.txt
              export ROUTER_CONTROLLER_CONFIG=/config/config.yaml
              export PYTHONPATH=/workload/mount/controller
              python3 -m controllerApp.main
          ports:
            - containerPort: {{ .Values.ports.routerController }}
          volumeMounts:
            - name: workload-mount
              mountPath: /workload/mount
            - name: router-runtime
              mountPath: /config
      volumes:
        - name: workload
          configMap:
            name: {{ include "router.complexName" . }}-workload
        - name: router-runtime
          configMap:
            name: {{ include "router.complexName" . }}-router-runtime
        - name: workload-mount
          emptyDir: {}
