# Copyright © Advanced Micro Devices, Inc., or its affiliates.
  #
  # SPDX-License-Identifier: MIT

{{- if .Values.stunner.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "release.fullname" . }}-stunner
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    group: stunner.l7mp.io
    kind: GatewayConfig
    name: {{ include "release.fullname" . }}-stunner-config
    namespace: {{ .Release.Namespace }}
{{- end }}
