# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

http_route:
  enabled: false
  gateway:
    name: https
    namespace: kgateway-system

replicaCount: 1
enableUI: true

images:
  pythonBase: python:3.11-slim
ports:
  routerController: 8084
  routerClassifier: 8010
  ui: 8008

deployDemonstrationLLMs: false

primary:
  image: "amdenterpriseai/aim-meta-llama-llama-3-1-8b-instruct:0.11.1"
  env_vars:
    AIM_PRECISION: "fp8"

secondary:
  image: "amdenterpriseai/aim-meta-llama-llama-3-3-70b-instruct:0.11.1"
  env_vars:
    AIM_PRECISION: "fp8"

# NOTE: Any number of models with arbitrary names can be declared in this section.
# You can add as many models as needed, each with a unique name and corresponding configuration.
models:
- name: primary
  base_url: http://primary
  api_key: "" # optional
  api_key_secret_ref: {} # optional: {name: <secret-name>, key: <secret-key>}
  model_name: "" # optional
- name: secondary
  base_url: http://secondary
  api_key: "" # optional
  api_key_secret_ref: {} # optional: {name: <secret-name>, key: <secret-key>}
  model_name: "" # optional

routing:
  rules:
    task_router:
      classifier_path: /classify
      classes:
        Code Generation:
          backend: secondary
          description: "Any request to create, write, generate, implement or provide code in any programming language, algorithm implementations, scripts, functions, or code examples. Also includes 'how to code X', 'write a program that'."
        Summarization:
          backend: primary
          description: "Tasks related to summarizing text, condensing articles, conversations, documents, providing key points or brief overviews."
        Unknown:
          backend: primary
          description: "Requests that are completely unclear, off-topic, spam, or do not match ANY of the defined categories at all. Use only as last resort when the message has no relation to other categories."

    complexity_router:
      classifier_path: /classify
      classes:
        Hard:
          backend: secondary
          description: "High-effort tasks: algorithms, complex math, deep multi-step reasoning, code writing, advanced technical topics."
        Middle:
          backend: secondary
          description: "Medium effort tasks: short explanations, standard how-to questions, everyday problem solving, moderate knowledge recall."
        Easy:
          backend: primary
          description: "Very low-effort interactions: greetings, simple yes/no questions, basic facts, casual chat. No deep thinking required."
        Unknown:
          backend: primary
          description: "Requests that are completely unclear, off-topic, spam, or do not match ANY of the defined categories at all. Use only as last resort when the message has no relation to other categories."

classifier:
  llmBackend: secondary

logLevel: "DEBUG"

secrets:
  # full | user_only
  CLASSIFIER_CONTEXT_MODE: full
  # quantity of last messages for context classifier
  CLASSIFIER_CONTEXT_TURNS: 5

storage:
  ephemeral:
    storageClassName: null
    quantity: 1Gi
  dshm:
    sizeLimit: 1Gi

embedding:
  enabled: true
  metadata:
    labels: {}
  image: "michaelf34/infinity:0.0.70-amd-gfx942"
  model: "intfloat/multilingual-e5-large-instruct"
  gpus: 1
  resources:
    requests: { cpu: "2", memory: "32Gi" }
    limits: { cpu: "4", memory: "192Gi" }
  storage:
    ephemeral:
      quantity: 20Gi
    dshm:
      sizeLimit: 16Gi
  deployment:
    ports:
      http: 7997
    command:
      - infinity_emb
    args:
      - v1
      - server
