# Copyright © Advanced Micro Devices, Inc., or its affiliates.
#
# SPDX-License-Identifier: MIT

apiVersion: v2
name: aimsb-fsi
description: Financial Stock Intelligence blueprint
type: application
version: 0.4.4
maintainers:
- name: AMD
  url: https://www.amd.com/
dependencies:
- name: aimchart-llm
  version: 0.2.1
  repository: oci://registry-1.docker.io/amdenterpriseai
  alias: llm
annotations:
  org.opencontainers.image.vendor: AMD
  com.amd.aim.release.notes: "Update AIM version"
  com.amd.aim.description.full: "A sophisticated financial analysis tool that combines real-time stock data, technical indicators, and Large Language Model (LLM) analysis to provide comprehensive stock insights."
  com.amd.aim.hfToken.required: "not-applicable"
  com.amd.aim.title: "Financial Stock Intelligence"
